# ============================================================================
# Order Service Configuration
# ============================================================================
# Creates orders from carts, manages order lifecycle (state machine),
# handles payment integration, and coordinates installation scheduling.
#
# Links:
#   - DevelopmentPlan.xml#DP-SVC-order-service
#   - RequirementsAnalysis.xml#UC-ORDER-PLACE
#   - RequirementsAnalysis.xml#UC-ORDER-TRACK
#   - RequirementsAnalysis.xml#UC-ORDER-CANCEL
#   - Technology.xml#TECH-yookassa
# ============================================================================

server:
  port: 8084

grpc:
  server:
    port: 9084
  client:
    cart-service:
          address: ${CART_SERVICE_GRPC_ADDRESS:static://localhost:9083}
          negotiation-type: PLAINTEXT
          enable-keep-alive: true

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: orders

# -----------------------------------------------------------------------------
# gRPC Clients
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# YooKassa Payment Gateway Configuration
# -----------------------------------------------------------------------------
yookassa:
  shop-id: ${YOOKASSA_SHOP_ID:}
  secret-key: ${YOOKASSA_SECRET_KEY:}
  # API endpoints (defaults to production)
  api-url: ${YOOKASSA_API_URL:https://api.yookassa.ru/v3}
  # Webhook verification
  webhook:
    enabled: true
    secret: ${YOOKASSA_WEBHOOK_SECRET:}
  # Payment settings
  payment:
    # Two-stage payment for production orders (authorize, then capture)
    capture: false
    # Auto-capture timeout (YooKassa will auto-cancel if not captured)
    auto-capture-timeout-hours: 168  # 7 days
    # Default payment methods
    default-payment-methods:
      - bank_card
      - yoo_money
      - sbp
      - sberbank
    # Receipt generation (54-FZ compliance)
    receipt:
      enabled: true
      tax-system-code: 1  # General tax system
      vat-code: 2  # 20% VAT
  # Retry configuration
  retry:
    max-attempts: 3
    backoff-ms: 1000

# -----------------------------------------------------------------------------
# Order Domain Configuration
# -----------------------------------------------------------------------------
order:
  # Idempotency key TTL for order placement
  idempotency:
    key-ttl-hours: 24

  # Order state machine configuration
  state-machine:
    # Allowed transitions are defined in domain; this is for logging/metrics
    log-transitions: true

  # Cancellation policy
  cancellation:
    allowed-before-status: SHIPPED
    refund-processing-days: 5

  # Order number generation
  number-format: "KAN-{YYYYMMDD}-{SEQ:6}"

# -----------------------------------------------------------------------------
# Kafka Topics
# -----------------------------------------------------------------------------
kafka:
  topics:
    order-created: order.created
    order-confirmed: order.confirmed
    order-shipped: order.shipped
    order-delivered: order.delivered
    order-completed: order.completed
    order-cancelled: order.cancelled
    payment-applied: order.payment.applied

# -----------------------------------------------------------------------------
# Resilience4j
# -----------------------------------------------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      cartService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
      paymentGateway:
        sliding-window-size: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 30s
  retry:
    instances:
      cartService:
        max-attempts: 3
        wait-duration: 500ms
      paymentGateway:
        max-attempts: 3
        wait-duration: 1000ms
  timelimiter:
    instances:
      paymentGateway:
        timeout-duration: 30s

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
logging:
  level:
    com.kanokna.order_service.domain: DEBUG
    com.kanokna.order_service.application: DEBUG
    com.kanokna.order_service.adapters.out.gateway: INFO
