# ============================================================================
# Pricing Service Configuration
# ============================================================================
server:
  port: 8082

grpc:
  server:
    port: 9082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pricing}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: pricing

  # Redis for quote caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

# ─────────────────────────────────────────────────────────────────────────────
# Pricing Domain Configuration
# ─────────────────────────────────────────────────────────────────────────────
pricing:
  # Quote caching
  quote-cache:
    enabled: true
    ttl-minutes: 5
    key-prefix: "quote:"

  # Default currency
  default-currency: RUB

  # Tax configuration
  tax:
    default-vat-rate: 20  # 20% VAT in Russia
    included-in-price: true

  # Campaign evaluation
  campaigns:
    max-stack: 1  # Maximum campaigns that can stack
    check-validity: true

  # Price calculation precision
  precision:
    decimal-places: 2
    rounding-mode: HALF_UP

# ─────────────────────────────────────────────────────────────────────────────
# Kafka Topics
# ─────────────────────────────────────────────────────────────────────────────
kafka:
  topics:
    quote-calculated: pricing.quote.calculated
    price-book-updated: pricing.pricebook.updated

# ─────────────────────────────────────────────────────────────────────────────
# Logging - Price Decision Trace
# ─────────────────────────────────────────────────────────────────────────────
logging:
  level:
    com.kanokna.pricing_service.domain.service: DEBUG
