# ============================================================================
# Reporting Service Configuration
# ============================================================================
# Aggregates data for dashboards and reports. Uses read-optimized storage
# with materialized views for analytics queries.
#
# Links:
#   - DevelopmentPlan.xml#DP-SVC-reporting-service
#   - RequirementsAnalysis.xml#UC-REPORT-SALES
# ============================================================================

server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reporting}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: reporting

# -----------------------------------------------------------------------------
# Reporting Domain Configuration
# -----------------------------------------------------------------------------
reporting:
  # Report types
  reports:
    sales:
      enabled: true
      cache-ttl-minutes: 5
      max-date-range-days: 365
    conversion:
      enabled: true
      cache-ttl-minutes: 15
    product-performance:
      enabled: true
      cache-ttl-minutes: 30

  # Materialized view refresh
  materialized-views:
    refresh-on-startup: true
    concurrent-refresh: true
    schedules:
      daily-sales: "0 5 0 * * *"      # 00:05 daily
      weekly-summary: "0 0 1 * * MON"  # Monday 01:00
      monthly-summary: "0 0 2 1 * *"   # 1st of month 02:00

  # Export settings
  export:
    max-rows: 100000
    formats:
      - CSV
      - XLSX
    temp-directory: ${java.io.tmpdir}/kanokna-reports

  # Data retention
  retention:
    raw-events-days: 90
    aggregated-data-days: 730  # 2 years

# -----------------------------------------------------------------------------
# Kafka Consumer Configuration
# -----------------------------------------------------------------------------
kafka:
  consumer:
    group-id: reporting-service
  topics:
    order-created: order.created
    order-completed: order.completed
    order-cancelled: order.cancelled
    product-published: catalog.product.published

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
logging:
  level:
    com.kanokna.reporting_service.domain: DEBUG
    com.kanokna.reporting_service.application: DEBUG
