# ============================================================================
# Search Service Configuration
# ============================================================================
# Provides full-text and faceted search over product catalog using Elasticsearch.
# Indexes products asynchronously via domain events.
#
# Links:
#   - DevelopmentPlan.xml#DP-SVC-search-service
#   - RequirementsAnalysis.xml#UC-CATALOG-BROWSE
#   - RequirementsAnalysis.xml#NFR-PERF-SEARCH-LATENCY
#   - Technology.xml#TECH-elasticsearch
# ============================================================================

server:
  port: 8089

spring:
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}
    connection-timeout: 5s
    socket-timeout: 30s
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: search-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

# -----------------------------------------------------------------------------
# Search Domain Configuration
# -----------------------------------------------------------------------------
search:
  index:
    name: product_templates
    alias: product_templates
    version-prefix: product_templates_v
  reindex:
    batch-size: 200
    lock-name: search-service:reindex-lock

# -----------------------------------------------------------------------------
# Kafka Consumer Configuration
# -----------------------------------------------------------------------------
kafka:
  topics:
    product-published: catalog.product.published
    product-unpublished: catalog.product.unpublished
    product-updated: catalog.product.updated

# -----------------------------------------------------------------------------
# Resilience4j
# -----------------------------------------------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      elasticsearch:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  timelimiter:
    instances:
      elasticsearch:
        timeout-duration: 5s

# -----------------------------------------------------------------------------
# Logging
# -----------------------------------------------------------------------------
logging:
  level:
    com.kanokna.search.domain: DEBUG
    com.kanokna.search.application: DEBUG
    org.elasticsearch: INFO
